# Site settings
title: "Neil Lawrence's Talks"
email: N.Lawrence@sheffield.ac.uk
description: talks given by Neil Lawrence
baseurl: "/talks" # the subpath of your site, e.g. /blog/
# Exclude directories for preprocessing.
exclude:
  - slides/reveal.js/plugin/markdown/example
#  - slides/reveal.js/css/theme/
reveal:
  width: 512
  height: 384
youtube:
  width: 512
  height: 384
talk_files: "http://inverseprobability.com/talks/slides/"
nbviewer: "https://nbviewer.jupyter.org/"
basenb: "github/lawrennd/talks/blob/gh-pages/_notebooks/" 
url: "http://inverseprobability.com" # the base hostname & protocol for your site
twitter_username: lawrennd
github_username:  lawrennd

comments: true
disqus:
  shortname: inverseprobabilitycom
github:
  edit: true

permalink: "/:categories/:title.html"

analytics:
  google:
    tracking_id: UA-62968536-1

# Build settings
markdown: kramdown
future: true #false
